import Foundation

public struct Team: Codable {
    var avatar_url: String //": "https://cdn.dribbble.com/users/40433/avatars/normal/41b86a77ca368dd4a969397ef39ba9a6.png?1472167036",
    var bio: String //": "Digital Agency in SF, NY, LA and Iceland. Clients include Google, Reuters, Facebook, Uber, ESPN, Red Bull, Samsung, Airbnb, Lonely Planet, Verizon &amp; Dropbox. ",
    var buckets_count: Int //": 0,
    var buckets_url: String //": "https://api.dribbble.com/v1/users/40433/buckets",
    var can_upload_shot: Bool //": true,
    var comments_received_count: Int //": 4081,
    var created_at: Date //": "2011-06-14T01:42:09Z",
    var followers_count: Int //": 65674,
    var followers_url: String //": "https://api.dribbble.com/v1/users/40433/followers",
    var following_url: String //": "https://api.dribbble.com/v1/users/40433/following",
    var followings_count: Int //": 532,
    var html_url: String //": "https://dribbble.com/ueno",
    var id: Int //": 40433,
    var likes_count: Int //": 698,
    var likes_received_count: Int //": 155475,
    var likes_url: String //": "https://api.dribbble.com/v1/users/40433/likes",
    var links: Links
    var location: String //": "San Francisco, CA",
    var members_count: Int //": 28,
    var members_url: String //": "https://api.dribbble.com/v1/teams/40433/members",
    var name: String //": "ueno.",
    var pro: Bool //": false,
    var projects_count: Int //": 38,
    var projects_url: String //": "https://api.dribbble.com/v1/users/40433/projects",
    var rebounds_received_count: Int //": 31,
    var shots_count: Int //": 384,
    var shots_url: String //": "https://api.dribbble.com/v1/users/40433/shots",
    var team_shots_url: String //": "https://api.dribbble.com/v1/teams/40433/shots",
    var type: String //": "Team",
    var updated_at: Date //": "2017-09-20T21:33:32Z",
    var username: String //": "ueno"
}
